### ISSUE TITLE
Bug: get_list/1 skips leading empty cells

### ISSUE THREAD

**Issue by ZombieHarvester** [jsonkenl/xlsxir#69]
Table: "B1" = 2,  "D1" = 4

Xlsxir.get_list(table_id) incorrectly returns [[2, nil, 4]]

Expected to return [[nil, 2, nil, 4]]

**Comment by jsonkenl** [comment]
@ZombieHarvester, yes there is definitely a bug. The private function `Xlsxir.do_get_row/1` is actually returning `[["B1", 2], ["B1", nil], ["D1", 4]]` so there is an error in the logic related to filling the empty cells. I'm digging into it and will let you know when I figure something out. Thanks for the heads up.

**Comment by jsonkenl** [comment]
Ok @ZombieHarvester I think I got it. Could you please pull from master and test your file? Thanks!

**Comment by ZombieHarvester** [comment]
@jsonkenl seems to be working! Thanks

**Comment by jsonkenl** [comment]
Great! Closing this now, let me know if you have any other issues. I'll release this fix to Hex soon.
