### ISSUE TITLE
Trouble parsing a date field

### ISSUE THREAD

**Issue by radiospiel** [jsonkenl/xlsxir#75]
I have a xlsx file, which has a field with the content "01.05.2018". xlsxir parses this into `{2014, 4, 30}`. While changing the date from May 1st into Apr 30th could be explained as some timezone adjustment (note that this is Berlin, which is both german - i.e. uses DD.MM.YYYY - and UTC+1/UTC+2) the year change cannot be explained that way.

Any ideas how I could fix this? Is this a bug with xlsxir? I can easily provide the XLSX file if that helps.

**Comment by radiospiel** [comment]
Note that I do

    [ headers | rows ] = Xlsxir.stream_list(path, 0) |> Enum.map(fn s -> s end)

**Comment by jsonkenl** [comment]
@radiospiel Thanks for letting me know. I'll take a look as soon as possible and get back to you.

**Comment by radiospiel** [comment]
thank you, I appreciate that very much!

**Comment by jsonkenl** [comment]
@radiospiel it might help to have the xlsx file as I've been unable to reproduce the error. I've formatted a cell in a new workbook as DD.MM.YYYY and it's parsing it as {2018, 5, 1} for me.

**Comment by radiospiel** [comment]
@jsonkenl ah I missed the notification email, thanks for the speedy response :) So, here it is: 
[forum-bug.xlsx](https://github.com/jsonkenl/xlsxir/files/1954571/forum-bug.xlsx)

**Comment by jsonkenl** [comment]
@radiospiel My apologies for the delay. I've added this to my to-do for the weekend. I should have something for you soon.

**Comment by jsonkenl** [comment]
Hey @radiospiel, I think it has something to do with your regional date/time settings on your operating system or settings within Excel. I created a custom date field in a new workbook I opened up and the sequential serial number I get from 01.05.2018 using dd.mm.yyyy is '43221' while the sequential serial number from your workbook for the same date is '41759'. Only date formats that begin with an asterisk respond to changes in regional date and time settings. Custom dates to not. 

Xlsxir is designed to interpret dates where a serial date of '1' is equal to 1/1/1900. When I convert '1' to a date in your workbook, I get 1/2/1904.

**Comment by radiospiel** [comment]
@jsonkenl well, that sounds super weird, but I will pick deeper. If i find something I'll check back with you. In the meantime lets close this issue for now. Thanks for your help!

**Comment by radiospiel** [comment]
Me again :) It seems someone else also found out about this, see https://www.accountingweb.com/technology/excel/when-excel-dates-mysteriously-shift-by-4-years

**Comment by radiospiel** [comment]
@jsonkenl yea, I did this and it seems to do the trick. An enhancement in xlsxir would make it more awesome still :) Thanks for the good work!
