### ISSUE TITLE
Sheet name

### ISSUE THREAD

**Issue by alex88** [jsonkenl/xlsxir#78]
Is there a way to get the sheet name when extracting data?

**Comment by jsonkenl** [comment]
Hey @alex88, yes there is but Xlsxir is not currently capable of capturing it. The information is located in the `xl/workbook.xml` file within the .xlsx document. I'll need to parse that file anyway to fix the 1904 date issue from #75, so I'll add this as an enhancement to add to that one. Feel free to take a stab at it if you have any interest.

**Comment by norpan** [comment]
I made a quick implementation of a parser that puts worksheet names into an ets table. However, I'm not sure how to incorporate it into the API. Also, I used mix format so the diff is bigger than it should be. See https://github.com/norpan/xlsxir/tree/parse_workbook

**Comment by jsonkenl** [comment]
This has been implemented via PR #82
