### ISSUE TITLE
Fail to read the formula result

### ISSUE THREAD

**Issue by junjizhi** [jsonkenl/xlsxir#80]
Test file: [import-sheet-1.xlsx](https://github.com/jsonkenl/xlsxir/files/2290926/import-sheet-1.xlsx)

```
iex(36)> path = "./import-sheet-1.xlsx"
iex(37)> [{:ok, s1}|_] = Xlsxir.multi_extract(path)
[
  ok: #Reference<0.1526854273.1649541121.217868>,
  ok: #Reference<0.1526854273.1649541121.217870>
]
iex(38)> Xlsxir.get_list(s1)
[
  [nil, nil, nil],
  [nil, nil,
   "IFERROR(INDEX(INDIRECT(INDIRECT(ADDRESS(3,COLUMN()))&\"[uniqueKey]\"),MATCH(INDIRECT(ADDRESS(ROW(),COLUMN(),1,TRUE,\"object-input\")),INDIRECT(INDIRECT(ADDRESS(3,COLUMN()))&\"[name]\"),0)),IF(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN(),1,TRUE,\"object-input\"))), \"\", INDIRECT(ADDRESS(ROW(),COLUMN(),1,TRUE,\"object-input\"))))"]
]
```

It's expected to return the formula result which should be nil or empty string, but it returns the formula string instead.

**Comment by jsonkenl** [comment]
Hi @junjizhi, can you please carve out the cells causing the error into a new workbook and share it with me so that I can debug? Please test to make sure the error is reproduced in the new workbook.

**Comment by junjizhi** [comment]
[parse-bug.xlsx](https://github.com/jsonkenl/xlsxir/files/2291661/parse-bug.xlsx)

@jsonkenl In the file attached above, there's only one cell A1 in the "Sheet1" that has value. The rest of the workbook is blank. I can reproduce this bug with the above script.
