### ISSUE TITLE
 Collectable protocol is deprecated for non-empty lists

### ISSUE THREAD

**Issue by zpeters** [jsonkenl/xlsxir#87]
(Elixir 1.8)

I have difficulty reading elixir errors like this.  I think the warning is referring to the xlsxir code?  If not i can make a report somewhere else.   happy to help work on this if you accept pull requests..

<pre>
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (elixir) lib/enum.ex:1227: Enum.into_protocol/2
  (xlsxir) lib/xlsxir/parse_worksheet.ex:110: Xlsxir.ParseWorksheet.sax_event_handler/4
  (erlsom) c:/Users/XXXX/Projects/XXXXXX/deps/erlsom/src/erlsom_sax_utf8.erl:1408: :erlsom_sax_utf8.wrapCallback/2
  (erlsom) c:/Users/XXXX/Projects/XXXXXX/deps/erlsom/src/erlsom_sax_utf8.erl:907: :erlsom_sax_utf8.parseContentLT/2
</pre>

**Comment by michaelst** [comment]
would be nice to have this merged in https://github.com/jsonkenl/xlsxir/pull/86/files

**Comment by jsonkenl** [comment]
Thanks! I'll take a look ASAP.

**Comment by michaelst** [comment]
The PR was closed, not merged. Not sure if that was on purpose or not

**Comment by jsonkenl** [comment]
My bad, thanks! Trying to do this on my mobile and I hit the wrong button.

**Comment by michaelst** [comment]
No problem, thanks for being so responsive!
